service_names = {
    "0_8": "Home Cleaning Service",
    "10_9": "Office Cleaning & Maintenance",
    "11_11": "Carpet Shampooing",
    "12_7": "Electrical Repairs",
    "13_11": "AC Installation & Maintenance",
    "14_7": "Wall Painting",
    "15_1": "Home Renovation",
    "16_8": "Window Glass Cleaning",
    "17_5": "Furniture Polishing",
    "18_4": "Deep Kitchen Cleaning",
    "19_6": "Plumbing Service",
    "1_4": "Sofa Cleaning",
    "20_5": "Curtain Washing",
    "21_5": "Mattress Cleaning",
    "22_0": "Furniture Assembly",
    "23_10": "TV Mounting",
    "24_10": "Home Theater Setup",
    "25_0": "Electrical Wiring",
    "26_7": "Tile Repair & Grouting",
    "27_7": "Floor Polishing",
    "28_4": "Bathroom Deep Cleaning",
    "29_0": "Plumbing Fixture Installation",
    "2_0": "Appliance Installation",
    "30_2": "AC Gas Refill",
    "31_6": "Pipe Leakage Fix",
    "32_4": "Pest Control",
    "33_4": "Kitchen Exhaust Cleaning",
    "34_6": "Drain Unclogging",
    "35_11": "Sewage Line Cleaning",
    "36_1": "Interior Design Consultation",
    "37_0": "Lighting Installation",
    "38_4": "Kitchen Chimney Cleaning",
    "39_10": "Smart Home Setup",
    "3_5": "House Painting",
    "40_8": "Bathroom Sanitation Service",
    "41_3": "Moving & Packing Service",
    "42_1": "Roof Waterproofing",
    "43_2": "Garden Maintenance",
    "44_0": "Carpet Installation",
    "45_6": "Toilet Repair",
    "46_4": "Upholstery Cleaning",
    "47_7": "Wall Crack Fixing",
    "48_5": "Pest Removal & Fumigation",
    "49_1": "Interior Woodwork",
    "4_5": "Window Washing",
    "5_11": "Storage Cleaning",
    "6_7": "Door Frame Painting",
    "7_3": "Kitchen Renovation",
    "8_5": "Floor Waxing & Polishing",
    "9_4": "Carpet Deep Cleaning"
}

# Reverse mapping: service name -> service code
name_to_code = {v: k for k, v in service_names.items()}